import React from "react";
import { AbsoluteFill, Audio, Sequence, staticFile } from "remotion";
import { palette } from "./design/tokens";
import { useWorthlyFonts } from "./components/Fonts";
import { SCENES } from "./timeline";
import { OpeningScene } from "./scenes/OpeningScene";
import { ThesisScene } from "./scenes/ThesisScene";
import { BeforeScene } from "./scenes/BeforeScene";
import { WaitScene } from "./scenes/WaitScene";
import { DecideScene } from "./scenes/DecideScene";
import { PurchaseScene } from "./scenes/PurchaseScene";
import { TimeScene } from "./scenes/TimeScene";
import { AnytimeScene } from "./scenes/AnytimeScene";
import { ZoomOutScene } from "./scenes/ZoomOutScene";
import { InsightScene } from "./scenes/InsightScene";
import { PhilosophyScene } from "./scenes/PhilosophyScene";
import { EndScene } from "./scenes/EndScene";
import { PastPurchaseScene, PatternsScene, PrivacyScene, AppearanceScene, ReviewQueueScene, CorrectionScene } from "./scenes/FeatureScenes";
import { fontFamily } from "./design/typography";

const SCENE_COMPONENTS: Record<string, React.FC> = {
  opening: OpeningScene,
  thesis: ThesisScene,
  before: BeforeScene,
  wait: WaitScene,
  decide: DecideScene,
  purchase: PurchaseScene,
  time: TimeScene,
  anytime: AnytimeScene,
  zoomout: ZoomOutScene,
  insight: InsightScene,
  philosophy: PhilosophyScene,
  end: EndScene,
  past: PastPurchaseScene,
  patterns: PatternsScene,
  privacy: PrivacyScene,
  appearance: AppearanceScene,
  queue: ReviewQueueScene,
  correction: CorrectionScene,
};

/**
 * Worthly — 值不值.
 *
 * One continuous sheet of Worthly paper. Every scene fades its own content up
 * from that paper and back down to it, so the film never cuts between two
 * pictures; it dips to the page and comes back.
 *
 * The score is generated by `scripts/make-score.mjs` and written to
 * `public/audio/worthly-score.wav`. It is already mixed and loudness-calibrated
 * (−16 LUFS integrated), so nothing is trimmed here — the arrangement's own
 * dynamics follow the cut.
 */
export const WorthlyPromo: React.FC = () => {
  useWorthlyFonts();

  return (
    <AbsoluteFill style={{ background: palette.cream, willChange: "transform" }}>
      <Audio src={staticFile("audio/worthly-score.wav")} />
      {SCENES.map((scene) => {
        const Scene = SCENE_COMPONENTS[scene.id];
        if (!Scene) return null;
        return (
          <Sequence
            key={scene.id}
            from={scene.from}
            durationInFrames={scene.durationInFrames}
            name={scene.title}
          >
            <Scene />
          </Sequence>
        );
      })}
      <div style={{ position: "absolute", left: 150, bottom: 24, fontFamily: fontFamily.sans,
        fontSize: 18, color: palette.muted }}>功能演示 · 示例数据 · 界面依据当前 iOS App 重绘</div>
    </AbsoluteFill>
  );
};
